# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fish Properties
minecraft_version=1.6.4-MITE
yarn_mappings=1.6.4
loader_version=3.4.3

# Mod Properties
mod_version=1.0.0
mod_id=neresources
mod_name=NotEnoughResources
archives_base_name=NotEnoughResources

# Dependency Properties
emi_version=1.1.27

# Maven Properties
maven_group=org.moddedmite
# The maven id must be all lowercase and connected with "-"
maven_id=notenoughresources

fabric_version=0.91.1+1.20.4

# Run Properties
username=Dev
screen_width=854
screen_height=480
